#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config top_padding 45
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config border_width         5
bspc config focused_border_color \#81A1C1
bspc config normal_border_color \#EBEEF4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a viewnior state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore &
picom &
killall dunst &
dunst &
/usr/lib/lxpolkit/lxpolkit &
$HOME/.config/polybar/launch.sh &
